# Generated by Django 4.2.2 on 2023-06-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_pglist_createdby_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pglist',
            name='image',
            field=models.ImageField(upload_to='login/static/pglist_images'),
        ),
    ]
