# Generated by Django 4.2.2 on 2023-06-29 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_pglist_booked_by_pglist_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pglist',
            name='booked_by',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
